### PR TITLE
Fix for Raw Post

### PR DESCRIPTION
**Pull request by marcelto**

### CODE REVIEW

**Comment by cwoskoski** [comment]
Good fix. Actually just made the fix locally prior to seeing this PR.

**Comment by marcelto** [comment]
Thanks @cwoskoski, hopefully @wshafer will have a chance to review and merge it soon.  This is a nice package but it is pretty limited without a fix for POST.

**Comment by wshafer** [comment]
@marcelto  Not sure what going on with my GH notifications, but I apologize for the delay on this one. 

Thanks for PR.

**Comment by marcelto** [comment]
No worries @wshafer, thanks for merging it and thanks for writing this package.

**Pull request merged**
